name: Generate OpenAPI Spec

on: 
  push:
    branches:
      - main

jobs:
  extact-openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Extract OpenAPI spec
        run: python extract-openapi.py main:app

      - name: GIT commit and push openapi spec
        env: 
          CI_COMMIT_MESSAGE: CI generated openapi spec
          CI_COMMIT_AUTHOR: Github Action Bot
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
